title: Suyeon Lee
url: "https://suylab.github.io/"
baseurl: "/researcher/"

markdown: kramdown

tracking_id: #

remote_theme: suylab/suylab.github.io@gem

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Contact"
   link: "contact"
 - name: "Resume"
   link: "sylee_cv_20220107.pdf" # put your files in the assets directory
 - name: "About"
   link: ""
