title: Suyeon Lee
url: "https://suylab.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

remote_theme: ankitsultana/researcher@gem

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "CV"
   link: "resume_dummy.pdf"
